### ISSUE TITLE
Create SSL-Gateway for JSON-Server

### ISSUE THREAD

**Issue by steinmax** [if-03-01-C-fall-2019/webapp-modelrockets-by-siegl-and-rausch-schott#10]
This is a possible fix regarding #6.

### ToDo:
Create a PHP File on our server (JSON-server), that delegates the request to the JSON-Server.
It is needed for a secure HTTPS communication between our website and the JSON-Server.

**Comment by bauepete** [comment]
Why PHP? Is this some legacy label?

**Comment by steinmax** [comment]
> Why PHP? Is this some legacy label?

We created this issue because it could be a possible fix for #6. We're not quite sure anyway if we will use this approach.

**Comment by bauepete** [comment]
Did research on https://github.com/typicode/hotel not lead to any result?

**Comment by steinmax** [comment]
At the time we created this issue, it was not yet clear what we will do about the problem. So we just created this issue to save this possible fix.

We tried to use [hotel](https://github.com/typicode/hotel) today but unfortunately, it didn't work. We tried several related fixes, that didn't work as well.

**Comment by steinmax** [comment]
I will close this issue because it turned out that we will not use this
