### ISSUE TITLE
Collect questions for the quiz

### ISSUE THREAD

**Issue by Nydery** [if-03-01-C-fall-2019/webapp-modelrockets-by-siegl-and-rausch-schott#4]
Find questions and provide answers and save them on the JSON Server.

**Comment by steinmax** [comment]
Ok, how many Questions are we planing to collect? I thought about 30 to 40 @Nydery

**Comment by Nydery** [comment]
Sorry for the late response, I would say up to 30 would be a good amount.

**Comment by steinmax** [comment]
Okay! So far I have collected a total amount of 10 questions

**Comment by steinmax** [comment]
I have added more questions to the quiz. If we need more we can reopen this issue.
