### ISSUE TITLE
JSON Server not responding

### ISSUE THREAD

**Issue by Nydery** [if-03-01-C-fall-2019/webapp-modelrockets-by-siegl-and-rausch-schott#6]
### Problem:
Github either blocks or doesn't support HTTP requests. It only works via HTTPS.

### Options for fix:
1. Publish JSON Server with a certificate.
2. Search for free JSON Server Host.
3. Try passing the request through a PHP file (#10).

**Comment by steinmax** [comment]
I'll be trying to get it to work over https

**Comment by steinmax** [comment]
The JSON Server is now working as expected
